Main-grid.jsx 컴포넌트 분할 작업
08Injinji/Frontend pull request #13
Opened 2022-05-20 12:53 UTC by wonmin23231

하나의 컴포넌트로 합쳐져 있던 내용들을 
작은 단위의 컴포넌트로 분할하였습니다.

또한, styled 컴포넌트 중 사용하지 않는 것들을 삭제하였으며,
겹치는 스타일의 경우 새로운 styled 컴포넌트를 생성하여
코드 가독성을 높이는 작업을 하였습니다.

지금까지 제 생각에는 html 태그 안에 들어가는 css 구문이 
가독성을 떨어트릴 수 있다고 생각하여
css 스타일과 html 태그를 분리하여 코드를 작성하는 것을 선호하였습니다.

이렇게 css와 html을 완전히 분리시키는 방법에 단점이 있을가요?

2022-05-21 11:20 UTC, kdy1 requested changes

2022-05-21 11:20 UTC, kdy1 commented on src/pages/main-grid.jsx
> +  height: ${(props) => (props.height ? props.height : '700px')};
`${(props) => (props.height ?? '700px')}`

2022-05-21 11:20 UTC, kdy1 commented on src/pages/main-grid.jsx
> +  height: ${(props) => (props.height ? props.height : '700px')};
props.height 이 0 인 경우가 없다면 위처럼 쓰는 게 더 명확한 코드입니다

2022-05-21 11:20 UTC, kdy1 commented on src/pages/main-grid.jsx
> +  height: ${(props) => (props.height ? props.height : '700px')};
여기도 그렇습니다

2022-05-21 11:20 UTC, kdy1 commented on src/pages/main-grid.jsx
> +    return parseInt(Math.random() * length);
이렇게 하는 것보다 https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Math/random#%EB%91%90_%EA%B0%92_%EC%82%AC%EC%9D%B4%EC%9D%98_%EC%A0%95%EC%88%98_%EB%82%9C%EC%88%98_%EC%83%9D%EC%84%B1%ED%95%98%EA%B8%B0 같이 하는 게 맞습니다

2022-05-21 11:20 UTC, kdy1 commented on src/pages/main-grid.jsx
> +    return parseInt(Math.random() * length);
이 코드는 암시적 형변환과 언어 스펙상의 문제점으로 인해 작동하는 코드입니다

2022-05-21 11:20 UTC, kdy1 commented on src/pages/main-grid.jsx
> +    return parseInt(Math.random() * length);
추후 유지 보수할 때나 코드를 읽을 때 문제가 될 수 있습니다

2022-05-22 04:51 UTC, wonmin23231 commented on src/pages/main-grid.jsx
> +  height: ${(props) => (props.height ? props.height : '700px')};
찾아보니 널 병합 연산자 라고 부르는 문법이네요.
널 병합 연산자나 옵셔널 체이닝 같이 비교적 최신 문법은 어디서 정보를 가져오시나요?

2022-05-22 07:34 UTC, kdy1 commented on src/pages/main-grid.jsx
> +  height: ${(props) => (props.height ? props.height : '700px')};
저런 문법들은 ECMAScript 표준이기 때문에 새로운 버전이 발표되면 그 내용을 다루는 블로그 포스트가 굉장히 많이 나옵니다

https://blog.outsider.ne.kr/

이 블로그 괜찮더라구요

2022-06-11 13:02 UTC, merged